api_platform:
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity/API']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']