security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        IS_AUTHENTICATED_FULLY: IS_AUTHENTICATED_ANONYMOUSLY
    providers:
        in_memory:
            memory:
                users:
                    sergey:
                        password: 12345678
                        roles: 'IS_AUTHENTICATED_FULLY'
    firewalls:
          login:
              provider: in_memory
              pattern:  ^/api/token
              stateless: true
              anonymous: true
              form_login:
                  check_path:               /api/token
                  success_handler:          lexik_jwt_authentication.handler.authentication_success
                  failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                  require_previous_session: false
          api_docs:
              pattern: ^/api/docs
              security: false
          api:
              pattern:   ^/api
              stateless: true
              guard:
                  authenticators:
                      - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/api/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }